version = 1

[[annotations]]
path = [
  "flake.nix",
  "flake.lock",
  ".gitignore",
  ".gitmodules",
  "REUSE.toml",
  ".github/**/",
  ".vscode/**/",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 thedavidmeister"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
