name: Rainix CI check shell
on: [push]

jobs:
  rainix-check-shell:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # intel mac
          macos-13,
          # apple silicon
          macos-latest
        ]
        include:
          # Only run tauri-shell shellhook tests for macos
          - os: macos-13
            task: nix develop .#tauri-shell -c bats shellhook.test.bats
          - os: macos-latest
            task: nix develop .#tauri-shell -c bats shellhook.test.bats
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop --command cargo release --version
      - run: nix develop --command flamegraph --help
      - run: nix develop --command graph --version
      - run: nix develop --command goldsky --version

      # Run on macOS only
      - name: tauri-shell shellhook tests
        run: ${{ matrix.task }}
        working-directory: test/fixture/devshell/tauri
