name: rainix-sol-legal
on:
  workflow_call:
jobs:
  legal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
      - name: Install soldeer dependencies
        if: hashFiles('soldeer.lock') != ''
        run: nix develop github:rainlanguage/rainix#sol-shell -c forge soldeer install
      - run: nix develop github:rainlanguage/rainix#sol-shell -c reuse lint
