name: Rainix CI
on: [push]
jobs:
  rainix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: ["cargo test", "cargo build --release"]
        include:
          # Solidity doesn't need to be tested on multiple platforms.
          - os: ubuntu-latest
            task: forge test -vvv
          - os: ubuntu-latest
            task: slither .
          - os: ubuntu-latest
            task: forge fmt --check
          - os: ubuntu-latest
            task: reuse lint
          - os: ubuntu-latest
            task: rainix-sol-artifacts
          # We don't need to do rust static analysis on multiple platforms.
          - os: ubuntu-latest
            task: rainix-rs-static
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      DEPLOYMENT_KEY: ${{ secrets.PRIVATE_KEY }}
    defaults:
      run:
        working-directory: test/fixture
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 8G
      - run: nix develop ../.. --command forge soldeer install
      - name: Run ${{ matrix.task }}
        env:
          ETH_RPC_URL: ${{ secrets.CI_DEPLOY_SEPOLIA_RPC_URL || vars.CI_DEPLOY_SEPOLIA_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.EXPLORER_VERIFICATION_KEY }}
        run: nix develop ../.. --command ${{ matrix.task }}
